### ISSUE TITLE
Install hangs during initialization 

### ISSUE THREAD

**Issue by tonydm** [blend-os/blendOS#88] opened 2023-08-10 19:25 UTC
I burned the blendos.iso using etcher to a samsung 128gb usb.  Booted to usb and install initialization starts but hangs/fails just after `Hostname Service` and msg `...AER:   Error of this Agent reported first`.   I have no idea what this represents.  I have tried downloading the KDE iso again with no boot success.  I've tried the Gnome version, same failure.  I have tried a smaller capacity USB Thumb drive my last attempt using a 4GB thumb drive.  I have other iso's/drives that boot via UEFI and have no issues.  I am excited to try BlendOS, but DOA :(

Thank you

inxi output w/ relative info
```
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: ROG CROSSHAIR VII HERO (WI-FI) v: Rev 1.xx
    serial: <superuser required> UEFI: American Megatrends v: 5102
    date: 05/31/2023
CPU:
  Info: 8-core model: AMD Ryzen 7 2700X bits: 64 type: MT MCP cache:
    L2: 4 MiB
  Speed (MHz): avg: 2274 min/max: 2200/3700 cores: 1: 2200 2: 3700 3: 1795
    4: 2200 5: 2196 6: 2200 7: 1886 8: 2200 9: 2200 10: 2614 11: 2200 12: 2200
    13: 2200 14: 2200 15: 2200 16: 2200
Graphics:
  Device-1: NVIDIA GK208B [GeForce GT 710] driver: nvidia v: 470.199.02
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia resolution:
    1: 1920x1200~60Hz 2: 1920x1200~60Hz
  OpenGL: renderer: NVIDIA GeForce GT 710/PCIe/SSE2
    v: 4.6.0 NVIDIA 470.199.02
Drives:
  Local Storage: total: 6.37 TiB used: 171.61 GiB (2.6%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 EVO 1TB
    size: 931.51 GiB
  ID-2: /dev/sda vendor: Western Digital model: WD10EFRX-68JCSN0
    size: 931.51 GiB
  ID-3: /dev/sdb vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB
  ID-4: /dev/sdc vendor: Western Digital model: WD2003FYYS-02W0B1
    size: 1.82 TiB
  ID-5: /dev/sdd vendor: Samsung model: SSD 860 EVO 2TB size: 1.82 TiB
  ID-6: /dev/sde type: USB model: General UDisk size: 3.87 GiB  <<<----- ****BOOTING TO BlendOS w/ this USB ****
```

![PXL_20230810_191111464](https://github.com/blend-os/blendOS/assets/1261605/4eefdeee-2b51-452a-804a-7a88bd77562e)

**Comment by frankenstein91** [comment] 2023-09-10 14:23
![grafik](https://github.com/blend-os/blendOS/assets/2527348/19733355-23f9-4dfc-808c-c18e93e19207)
same for me

**Comment by tonydm** [comment] 2023-09-10 15:53
It appears that @RudraSwat has too many irons in the fire.  He's a brilliant young man but I fear he hasn't the discipline to manage multiple projects.  And, perhaps, there's other extenuating circumstances that we are not aware.  Looking at a couple pages of listed issues, I don't see a single response from @RudraSwat.  BlendOS is an awesome project and is/was much more exciting than VaniliaOS.  But alas, I fear he's abandoned it.  Looking back at his projects activity, I see very little activity.  Too bad.  I'm going to move on for now and perhaps sometime in the future we'll see this project take shape, if someone else hasn't.  Best

**Comment by RudraSwat** [comment] 2023-09-10 17:04
Hi, I usually don't monitor the issues on this repo, just the ones against the individual repositories. blendOS is nowhere near abandoned, and I'm thinking of features for the next release. I haven't been able to reproduce this on any of my systems, and only just noticed this bug from an email from GitHub since you tagged me. Could you, perhaps, join the Discord server for blendOS and mention this issue there just to confirm it's not an issue only for you? Thanks :)

**Comment by frankenstein91** [comment] 2023-09-10 18:35
Hi @RudraSwat 

for me it is a clevo N130WU... I can not speak for @tonydm.
True is that we have both hanging systems.

- I have used 2 USB-Sticks and a DVD by now.
- zeroed my drives to prevent things loading from the old linux
- flashed my UEFI (what klilled my notebook) and send it back for repair
- redowloaded the ISOs many times

**Comment by frankenstein91** [comment] 2023-09-10 19:05
@tonydm do you have a WD NVME SSD?

**Comment by Ast3risk-ops** [comment] 2023-09-10 19:44
> It appears that @RudraSwat has too many irons in the fire. He's a brilliant young man but I fear he hasn't the discipline to manage multiple projects. And, perhaps, there's other extenuating circumstances that we are not aware. Looking at a couple pages of listed issues, I don't see a single response from @RudraSwat. BlendOS is an awesome project and is/was much more exciting than VaniliaOS. But alas, I fear he's abandoned it. Looking back at his projects activity, I see very little activity. Too bad. I'm going to move on for now and perhaps sometime in the future we'll see this project take shape, if someone else hasn't. Best

I understand your concern. He hasn't. I'm sorry he hasn't responded @tonydm, he's probably busy with school or something blendOS-related. I believe he's trying to get some fixes into ubuntu unity before the UI freeze.

Thanks for trying blend at least.

**Comment by Ast3risk-ops** [comment] 2023-09-10 19:44
also did you use etcher to flash the USB?

**Comment by frankenstein91** [comment] 2023-09-10 19:51
> also did you use etcher to flash the USB?

yes

**Comment by Ast3risk-ops** [comment] 2023-09-10 20:32
@frankenstein91 what happens when you wait for the systemd jobs to time out?

**Comment by frankenstein91** [comment] 2023-09-10 21:22
> @frankenstein91 what happens when you wait for the systemd jobs to time out?

they freeze

**Comment by frankenstein91** [comment] 2023-09-10 21:56
fixed by removing my NVME SSD and booting from DVD

**Comment by Ast3risk-ops** [comment] 2023-09-10 22:48
wow.

**Comment by RudraSwat** [comment] 2023-09-11 03:25
Ah great, I'll close this issue then.

**Closed** 2023-09-11 03:25 UTC

**Comment by tonydm** [comment] 2023-09-11 14:42
@RudraSwat - I wasn't able to follow up yesterday as I was otherwise unavailable.  With that said, my issue is not resolved so I'm curious why the issue "I opened" was Closed?

I'm pleased and excited to hear that the project is not dead and that you have plans to improve.  But with respect... you mentioned that you "don't monitor the issues on this repo".  Why?  That's what Github is for; to post a project and a place to discuss issues and handle Pulls and Merge Requests.   I get that Discord seems to be all the rage, but posting a project here and then effectively abandoning the "Issues" posted doesn't seem appropriate.

Then there's the issue I mentioned above.  Why you closed this issue?  Again, with respect, you seemed to have lost sight of the originator of the Issue.  I'm baffled

**Comment by tonydm** [comment] 2023-09-12 21:52
@frankenstein91 Thanks for that info.  I wasn't aware.  The 970 NVME is my primary drive and I was using the 870 SSD to test.  I'll pass for now.  It's not hoop I want to jump through at this time for my daily driver.  But thanks
