### ISSUE TITLE
support for BIOS

### ISSUE THREAD

**Issue by tifasoftware** [blend-os/blendOS#5] opened 2023-01-27 17:43 UTC
The iso won't boot in BIOS mode and only works in UEFI.

I found this issue out in VMWare

**Comment by definetly-not-carl** [comment] 2023-01-27 17:55
Hi, I am currently installing it in VirtualBox. I had the same problem, but I checked the box that said "enable EFI" and it just works.
I think there isn't a BIOS mode yet. It has been released yesterday after all

**Comment by RudraSwat** [comment] 2023-01-27 19:17
Duplicate of #1. Closing.

**Closed by RudraSwat** 2023-01-27 19:17 UTC
