### ISSUE TITLE
Make it possible to make changes to the immutable system

### ISSUE THREAD

**Issue by MichaelTrip** [blend-os/blendOS#10] opened 2023-01-28 21:45 UTC
Hi there,

i wonder if it is possible to make certain changes to the immutable system? I have to install some packages like the spice-vdagentd and the qemu-guest-tools in order for Virt-manager to pick up the correct screen resolution. How do i do that?

**Comment by pragmaticmero** [comment] 2023-01-29 18:07
Yep, it is possible to do that, I'll tell you how can you do that after I take a quick shit.

**Comment by pragmaticmero** [comment] 2023-01-29 18:27
Ahhh I feel lighter. Anyways

You can disable the immutability with this command

`sudo nearly enter rw`

After that you can install your QEMU/virt-manager stack nativelly in the OS with this command

`PATH=/usr/bin sudo pacman -S qemu-guest-tools`

or any app you want nativelly, you can decide that yourself.
And for enabling the immutability again, this is the command you have to run

`sudo nearly enter ro`

This is it.

Duplicate of #14

**Comment by jeff8970b** [comment] 2023-01-31 12:54
Hi there,

i tried to install open-vm-tools (Virtualbox) according to this, but the system doesnt use them.

As a suggestion, you could install/activate them in the iso, since most people will use a virtual machine to test your OS anyway.
Or at least give the option like vanillaOS does during installer.

Thx

**Closed** 2024-10-26 19:14 UTC
